package ch.threema.app.emojis

/**
 * Generated by Threema emoji-tools.
 */
object EmojiCategoryType {
    const val RECENT = 0
    const val SMILEYS = 1
    const val PEOPLE = 2
    const val NATURE = 3
    const val FOOD = 4
    const val ACTIVITY = 5
    const val TRAVEL = 6
    const val OBJECTS = 7
    const val SYMBOLS = 8
    const val FLAGS = 9
}
