/*  _____ _
 * |_   _| |_  _ _ ___ ___ _ __  __ _
 *   | | | ' \| '_/ -_) -_) '  \/ _` |_
 *   |_| |_||_|_| \___\___|_|_|_\__,_(_)
 *
 * Threema for Android
 * Copyright (c) 2017-2025 Threema GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package ch.threema.app.emojis;

/**
 * Generated by Threema emoji-tools.
 */
public class EmojiCategoryType {
    public static final int RECENT = 0;
    public static final int SMILEYS = 1;
    public static final int PEOPLE = 2;
    public static final int NATURE = 3;
    public static final int FOOD = 4;
    public static final int ACTIVITY = 5;
    public static final int TRAVEL = 6;
    public static final int OBJECTS = 7;
    public static final int SYMBOLS = 8;
    public static final int FLAGS = 9;
}
