/*  _____ _
 * |_   _| |_  _ _ ___ ___ _ __  __ _
 *   | | | ' \| '_/ -_) -_) '  \/ _` |_
 *   |_| |_||_|_| \___\___|_|_|_\__,_(_)
 *
 * Threema for Android
 * Copyright (c) 2017-2020 Threema GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package ch.threema.app.emojis;

/**
 * Generated by Threema emoji-tools.
 */
public class EmojiCategoryType {
	public static int RECENT = 0;
	public static int PEOPLE = 1;
	public static int NATURE = 2;
	public static int FOOD = 3;
	public static int ACTIVITY = 4;
	public static int TRAVEL = 5;
	public static int OBJECTS = 6;
	public static int SYMBOLS = 7;
	public static int FLAGS = 8;
}
