package ch.threema.app.emojis

/**
 * This class contains metadata about an emoji category
 *
 * Generated by Threema emoji-tools.
 */
data class EmojiCategory(
    @JvmField val category: Int,
    @JvmField val emojiInfos: List<EmojiInfo>,
)
