/*  _____ _
 * |_   _| |_  _ _ ___ ___ _ __  __ _
 *   | | | ' \| '_/ -_) -_) '  \/ _` |_
 *   |_| |_||_|_| \___\___|_|_|_\__,_(_)
 *
 * Threema for Android
 * Copyright (c) 2017-2025 Threema GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package ch.threema.app.emojis

/**
 * Generated by Threema emoji-tools.
 */
object EmojiCategoryType {
    const val RECENT = 0
    const val SMILEYS = 1
    const val PEOPLE = 2
    const val NATURE = 3
    const val FOOD = 4
    const val ACTIVITY = 5
    const val TRAVEL = 6
    const val OBJECTS = 7
    const val SYMBOLS = 8
    const val FLAGS = 9
}
