package ch.threema.app.emojis

/**
 * This class contains the coordinates of an emoji inside the sprite map.
 *
 * Generated by Threema emoji-tools. Do not modify!
 */
data class SpriteCoordinates(
    @JvmField val groupId: Int,
    @JvmField val spritemapId: Int,
    @JvmField val x: Int,
    @JvmField val y: Int,
)
